Now you should run one of the following depending on your shell
source /share/apps/python/miniconda3.9/etc/profile.d/conda.sh
source /share/apps/python/miniconda3.9/etc/profile.d/conda.csh
Traceback (most recent call last):
  File "/people/beec613/.conda/envs/jax-gpu/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/beec613/Desktop/pnnl_research/code/damiens_code/Pendulum_DD/Pendulum_DD/data.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/people/beec613/pnnl_research/code/damiens_code/Pendulum_DD/Pendulum_DD/onet_scripts/train_MF_EWC_script.py", line 123, in <module>
    d_vx = scipy.io.loadmat("C:/Users/beec613/Desktop/pnnl_research/code/damiens_code/Pendulum_DD/Pendulum_DD/data.mat")
  File "/people/beec613/.conda/envs/jax-gpu/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/people/beec613/.conda/envs/jax-gpu/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/people/beec613/.conda/envs/jax-gpu/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/people/beec613/.conda/envs/jax-gpu/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/beec613/Desktop/pnnl_research/code/damiens_code/Pendulum_DD/Pendulum_DD/data.mat'
