Now you should run one of the following depending on your shell
source /share/apps/python/miniconda3.9/etc/profile.d/conda.sh
source /share/apps/python/miniconda3.9/etc/profile.d/conda.csh

CondaValueError: The target prefix is the base prefix. Aborting.

Could not find conda environment: jax-cuda
You can list all discoverable environments with `conda info --envs`.

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /share/apps/python/miniconda3.9

  added / updated specs:
    - scipy=1.10.0


The following NEW packages will be INSTALLED:

  appdirs            pkgs/main/noarch::appdirs-1.4.4-pyhd3eb1b0_0
  blas               pkgs/main/linux-64::blas-1.0-mkl
  boltons            pkgs/main/linux-64::boltons-23.0.0-py39h06a4308_0
  intel-openmp       pkgs/main/linux-64::intel-openmp-2021.4.0-h06a4308_3561
  jsonpatch          pkgs/main/noarch::jsonpatch-1.32-pyhd3eb1b0_0
  jsonpointer        pkgs/main/noarch::jsonpointer-2.1-pyhd3eb1b0_0
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-11.2.0-h00389a5_1
  libgfortran5       pkgs/main/linux-64::libgfortran5-11.2.0-h1234567_1
  mkl                pkgs/main/linux-64::mkl-2021.4.0-h06a4308_640
  mkl-service        pkgs/main/linux-64::mkl-service-2.4.0-py39h7f8727e_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.3.1-py39hd3c417c_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.2.2-py39h51133e4_0
  numpy              pkgs/main/linux-64::numpy-1.24.3-py39h14f4228_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.24.3-py39h31eccc5_0
  packaging          pkgs/main/linux-64::packaging-23.0-py39h06a4308_0
  pluggy             pkgs/main/linux-64::pluggy-1.0.0-py39h06a4308_1
  pooch              pkgs/main/noarch::pooch-1.4.0-pyhd3eb1b0_0
  ruamel.yaml        pkgs/main/linux-64::ruamel.yaml-0.17.21-py39h5eee18b_0
  ruamel.yaml.clib   pkgs/main/linux-64::ruamel.yaml.clib-0.2.6-py39h5eee18b_1
  scipy              pkgs/main/linux-64::scipy-1.10.0-py39h14f4228_1
  toolz              pkgs/main/linux-64::toolz-0.12.0-py39h06a4308_0

The following packages will be UPDATED:

  ca-certificates                       2021.7.5-h06a4308_1 --> 2023.05.30-h06a4308_0
  certifi                          2021.5.30-py39h06a4308_0 --> 2023.5.7-py39h06a4308_0
  conda                               4.10.3-py39h06a4308_0 --> 23.5.0-py39h06a4308_0
  libgcc-ng                               9.3.0-h5101ec6_17 --> 11.2.0-h1234567_1
  libgomp                                 9.3.0-h5101ec6_17 --> 11.2.0-h1234567_1
  libstdcxx-ng                            9.3.0-hd4cf53a_17 --> 11.2.0-h1234567_1
  openssl                                 1.1.1k-h27cfd23_0 --> 1.1.1u-h7f8727e_0


Proceed ([y]/n)? 
Preparing transaction: ...working... done
Verifying transaction: ...working... failed

EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: /share/apps/python/miniconda3.9
  uid: 317989
  gid: 100


Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /qfs/people/beec613/.local/lib/python3.9/site-packages (23.1.2)
Defaulting to user installation because normal site-packages is not writeable
Looking in links: https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
Requirement already satisfied: jax[cuda11_pip] in /qfs/people/beec613/.local/lib/python3.9/site-packages (0.4.12)
Requirement already satisfied: ml-dtypes>=0.1.0 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from jax[cuda11_pip]) (0.2.0)
Requirement already satisfied: numpy>=1.21 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from jax[cuda11_pip]) (1.25.0)
Requirement already satisfied: opt-einsum in /qfs/people/beec613/.local/lib/python3.9/site-packages (from jax[cuda11_pip]) (3.3.0)
Requirement already satisfied: scipy>=1.7 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from jax[cuda11_pip]) (1.10.1)
Requirement already satisfied: importlib-metadata>=4.6 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from jax[cuda11_pip]) (6.7.0)
Requirement already satisfied: jaxlib==0.4.12+cuda11.cudnn86 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from jax[cuda11_pip]) (0.4.12+cuda11.cudnn86)
Collecting nvidia-cublas-cu11>=11.11 (from jax[cuda11_pip])
  Using cached nvidia_cublas_cu11-11.11.3.6-py3-none-manylinux1_x86_64.whl (417.9 MB)
Collecting nvidia-cuda-cupti-cu11>=11.8 (from jax[cuda11_pip])
  Using cached nvidia_cuda_cupti_cu11-11.8.87-py3-none-manylinux1_x86_64.whl (13.1 MB)
Requirement already satisfied: nvidia-cuda-nvcc-cu11>=11.8 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from jax[cuda11_pip]) (11.8.89)
Collecting nvidia-cuda-runtime-cu11>=11.8 (from jax[cuda11_pip])
  Using cached nvidia_cuda_runtime_cu11-11.8.89-py3-none-manylinux1_x86_64.whl (875 kB)
Collecting nvidia-cudnn-cu11>=8.8 (from jax[cuda11_pip])
  Using cached nvidia_cudnn_cu11-8.9.2.26-py3-none-manylinux1_x86_64.whl (732.3 MB)
Requirement already satisfied: nvidia-cufft-cu11>=10.9 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from jax[cuda11_pip]) (10.9.0.58)
Requirement already satisfied: nvidia-cusolver-cu11>=11.4 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from jax[cuda11_pip]) (11.4.0.1)
Requirement already satisfied: nvidia-cusparse-cu11>=11.7 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from jax[cuda11_pip]) (11.7.4.91)
Requirement already satisfied: zipp>=0.5 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from importlib-metadata>=4.6->jax[cuda11_pip]) (3.15.0)
Requirement already satisfied: setuptools in /qfs/projects/ops/rh7_gpu/python/miniconda3.9/lib/python3.9/site-packages (from nvidia-cusparse-cu11>=11.7->jax[cuda11_pip]) (52.0.0.post20210125)
Requirement already satisfied: wheel in /qfs/projects/ops/rh7_gpu/python/miniconda3.9/lib/python3.9/site-packages (from nvidia-cusparse-cu11>=11.7->jax[cuda11_pip]) (0.36.2)
Installing collected packages: nvidia-cuda-runtime-cu11, nvidia-cuda-cupti-cu11, nvidia-cublas-cu11, nvidia-cudnn-cu11
  Attempting uninstall: nvidia-cuda-runtime-cu11
    Found existing installation: nvidia-cuda-runtime-cu11 11.7.99
    Uninstalling nvidia-cuda-runtime-cu11-11.7.99:
      Successfully uninstalled nvidia-cuda-runtime-cu11-11.7.99
  Attempting uninstall: nvidia-cuda-cupti-cu11
    Found existing installation: nvidia-cuda-cupti-cu11 11.7.101
    Uninstalling nvidia-cuda-cupti-cu11-11.7.101:
      Successfully uninstalled nvidia-cuda-cupti-cu11-11.7.101
  Attempting uninstall: nvidia-cublas-cu11
    Found existing installation: nvidia-cublas-cu11 11.10.3.66
    Uninstalling nvidia-cublas-cu11-11.10.3.66:
      Successfully uninstalled nvidia-cublas-cu11-11.10.3.66
  Attempting uninstall: nvidia-cudnn-cu11
    Found existing installation: nvidia-cudnn-cu11 8.5.0.96
    Uninstalling nvidia-cudnn-cu11-8.5.0.96:
      Successfully uninstalled nvidia-cudnn-cu11-8.5.0.96
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.0.1 requires nvidia-cublas-cu11==11.10.3.66; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu11 11.11.3.6 which is incompatible.
torch 2.0.1 requires nvidia-cuda-cupti-cu11==11.7.101; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu11 11.8.87 which is incompatible.
torch 2.0.1 requires nvidia-cuda-runtime-cu11==11.7.99; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu11 11.8.89 which is incompatible.
torch 2.0.1 requires nvidia-cudnn-cu11==8.5.0.96; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu11 8.9.2.26 which is incompatible.
Successfully installed nvidia-cublas-cu11-11.11.3.6 nvidia-cuda-cupti-cu11-11.8.87 nvidia-cuda-runtime-cu11-11.8.89 nvidia-cudnn-cu11-8.9.2.26
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /share/apps/python/miniconda3.9

  added / updated specs:
    - tqdm


The following packages will be UPDATED:

  ca-certificates                       2021.7.5-h06a4308_1 --> 2023.05.30-h06a4308_0
  certifi                          2021.5.30-py39h06a4308_0 --> 2023.5.7-py39h06a4308_0
  openssl                                 1.1.1k-h27cfd23_0 --> 1.1.1u-h7f8727e_0
  tqdm               pkgs/main/noarch::tqdm-4.61.2-pyhd3eb~ --> pkgs/main/linux-64::tqdm-4.65.0-py39hb070fc8_0


Proceed ([y]/n)? 
Preparing transaction: ...working... done
Verifying transaction: ...working... failed

EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: /share/apps/python/miniconda3.9
  uid: 317989
  gid: 100


Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: torch in /qfs/people/beec613/.local/lib/python3.9/site-packages (2.0.1)
Requirement already satisfied: filelock in /qfs/people/beec613/.local/lib/python3.9/site-packages (from torch) (3.12.2)
Requirement already satisfied: typing-extensions in /qfs/people/beec613/.local/lib/python3.9/site-packages (from torch) (4.6.3)
Requirement already satisfied: sympy in /qfs/people/beec613/.local/lib/python3.9/site-packages (from torch) (1.12)
Requirement already satisfied: networkx in /qfs/people/beec613/.local/lib/python3.9/site-packages (from torch) (3.1)
Requirement already satisfied: jinja2 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from torch) (3.1.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from torch) (11.7.99)
Collecting nvidia-cuda-runtime-cu11==11.7.99 (from torch)
  Using cached nvidia_cuda_runtime_cu11-11.7.99-py3-none-manylinux1_x86_64.whl (849 kB)
Collecting nvidia-cuda-cupti-cu11==11.7.101 (from torch)
  Using cached nvidia_cuda_cupti_cu11-11.7.101-py3-none-manylinux1_x86_64.whl (11.8 MB)
Collecting nvidia-cudnn-cu11==8.5.0.96 (from torch)
  Using cached nvidia_cudnn_cu11-8.5.0.96-2-py3-none-manylinux1_x86_64.whl (557.1 MB)
Collecting nvidia-cublas-cu11==11.10.3.66 (from torch)
  Using cached nvidia_cublas_cu11-11.10.3.66-py3-none-manylinux1_x86_64.whl (317.1 MB)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from torch) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from torch) (10.2.10.91)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from torch) (11.4.0.1)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from torch) (11.7.4.91)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from torch) (2.14.3)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from torch) (11.7.91)
Requirement already satisfied: triton==2.0.0 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from torch) (2.0.0)
Requirement already satisfied: setuptools in /qfs/projects/ops/rh7_gpu/python/miniconda3.9/lib/python3.9/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch) (52.0.0.post20210125)
Requirement already satisfied: wheel in /qfs/projects/ops/rh7_gpu/python/miniconda3.9/lib/python3.9/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch) (0.36.2)
Requirement already satisfied: cmake in /qfs/people/beec613/.local/lib/python3.9/site-packages (from triton==2.0.0->torch) (3.26.4)
Requirement already satisfied: lit in /qfs/people/beec613/.local/lib/python3.9/site-packages (from triton==2.0.0->torch) (16.0.6)
Requirement already satisfied: MarkupSafe>=2.0 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /qfs/people/beec613/.local/lib/python3.9/site-packages (from sympy->torch) (1.3.0)
Installing collected packages: nvidia-cuda-runtime-cu11, nvidia-cuda-cupti-cu11, nvidia-cublas-cu11, nvidia-cudnn-cu11
  Attempting uninstall: nvidia-cuda-runtime-cu11
    Found existing installation: nvidia-cuda-runtime-cu11 11.8.89
    Uninstalling nvidia-cuda-runtime-cu11-11.8.89:
      Successfully uninstalled nvidia-cuda-runtime-cu11-11.8.89
  Attempting uninstall: nvidia-cuda-cupti-cu11
    Found existing installation: nvidia-cuda-cupti-cu11 11.8.87
    Uninstalling nvidia-cuda-cupti-cu11-11.8.87:
      Successfully uninstalled nvidia-cuda-cupti-cu11-11.8.87
  Attempting uninstall: nvidia-cublas-cu11
    Found existing installation: nvidia-cublas-cu11 11.11.3.6
    Uninstalling nvidia-cublas-cu11-11.11.3.6:
      Successfully uninstalled nvidia-cublas-cu11-11.11.3.6
  Attempting uninstall: nvidia-cudnn-cu11
    Found existing installation: nvidia-cudnn-cu11 8.9.2.26
    Uninstalling nvidia-cudnn-cu11-8.9.2.26:
      Successfully uninstalled nvidia-cudnn-cu11-8.9.2.26
Successfully installed nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-cupti-cu11-11.7.101 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /share/apps/python/miniconda3.9

  added / updated specs:
    - cudnn


The following NEW packages will be INSTALLED:

  cudatoolkit        pkgs/main/linux-64::cudatoolkit-11.3.1-h2bc3f7f_2
  cudnn              pkgs/main/linux-64::cudnn-8.2.1-cuda11.3_0

The following packages will be UPDATED:

  ca-certificates                       2021.7.5-h06a4308_1 --> 2023.05.30-h06a4308_0
  certifi                          2021.5.30-py39h06a4308_0 --> 2023.5.7-py39h06a4308_0
  openssl                                 1.1.1k-h27cfd23_0 --> 1.1.1u-h7f8727e_0


Proceed ([y]/n)? 
Preparing transaction: ...working... done
Verifying transaction: ...working... failed

EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: /share/apps/python/miniconda3.9
  uid: 317989
  gid: 100


Traceback (most recent call last):
  File "/people/beec613/pnnl_research/code/amandas_code/onet_scripts/train_MF_EWC_script.py", line 18, in <module>
    from utils_fs_v2 import timing,  DataGenerator, DataGenerator_res, DataGenerator_res2
  File "/qfs/people/beec613/pnnl_research/code/amandas_code/onet_scripts/utils_fs_v2.py", line 45, in <module>
    class DataGenerator(data.Dataset):
  File "/qfs/people/beec613/pnnl_research/code/amandas_code/onet_scripts/utils_fs_v2.py", line 47, in DataGenerator
    batch_size=64, rng_key=random.PRNGKey(1234)):
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/random.py", line 155, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/prng.py", line 406, in seed_with_impl
    return random_seed(seed, impl=impl)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/prng.py", line 690, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/prng.py", line 702, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/prng.py", line 707, in random_seed_impl_base
    return seed(seeds)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/prng.py", line 936, in threefry_seed
    return _threefry_seed(seed)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/pjit.py", line 250, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/pjit.py", line 163, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/core.py", line 2652, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/pjit.py", line 1193, in _pjit_call_impl
    return xc._xla.pjit(name, f, call_impl_cache_miss, [], [], donated_argnums,
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/pjit.py", line 1177, in call_impl_cache_miss
    out_flat, compiled = _pjit_call_impl_python(
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/pjit.py", line 1110, in _pjit_call_impl_python
    compiled = _pjit_lower(
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py", line 2329, in compile
    executable = UnloadedMeshExecutable.from_hlo(
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py", line 2651, in from_hlo
    xla_executable, compile_options = _cached_compilation(
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/interpreters/pxla.py", line 2561, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/dispatch.py", line 497, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/dispatch.py", line 465, in backend_compile
    return backend.compile(built_c, compile_options=options)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/people/beec613/pnnl_research/code/amandas_code/onet_scripts/train_MF_EWC_script.py", line 18, in <module>
    from utils_fs_v2 import timing,  DataGenerator, DataGenerator_res, DataGenerator_res2
  File "/qfs/people/beec613/pnnl_research/code/amandas_code/onet_scripts/utils_fs_v2.py", line 45, in <module>
    class DataGenerator(data.Dataset):
  File "/qfs/people/beec613/pnnl_research/code/amandas_code/onet_scripts/utils_fs_v2.py", line 47, in DataGenerator
    batch_size=64, rng_key=random.PRNGKey(1234)):
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/random.py", line 155, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/prng.py", line 406, in seed_with_impl
    return random_seed(seed, impl=impl)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/prng.py", line 690, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/core.py", line 380, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/prng.py", line 702, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/prng.py", line 707, in random_seed_impl_base
    return seed(seeds)
  File "/people/beec613/.local/lib/python3.9/site-packages/jax/_src/prng.py", line 936, in threefry_seed
    return _threefry_seed(seed)
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
